import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import {
  AlertTriangle,
  CheckCircle,
  Info,
  Loader2,
  XCircle,
} from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Toaster
          position="bottom-right"
          richColors
          closeButton
          expand={true}
          duration={3000}
          icons={{
            success: <CheckCircle className="h-4 w-4" />,
            error: <XCircle className="h-4 w-4" />,
            warning: <AlertTriangle className="h-4 w-4" />,
            info: <Info className="h-4 w-4" />,
            loading: <Loader2 className="h-4 w-4" />,
          }}
        />
        {children}
      </body>
    </html>
  );
}
